import Head from "next/head";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { z } from "zod";

const useSequentialState = <T,>(
  initialState: T,
): [() => T, (t: T) => void, T] => {
  let sequentialState = useRef(initialState);
  const [renderState, setRenderState] = useState(initialState);
  const setSequentialState = (newState: T) => {
    sequentialState.current = newState;

    setRenderState(newState);
  };
  const getSequentialState = () => {
    return sequentialState.current;
  };
  return [getSequentialState, setSequentialState, renderState];
};

const sleep = (time: number) => {
  return new Promise((resolve) => setTimeout(resolve, time));
};

export default function Home() {
  const [getSyntacticData, setSyntacticData, syntacticData] =
    useSequentialState([[], [], [], [], []] as Array<Array<string>>);
  const [prompt, setPrompt] = useState("Why is the sky so blue today?");

  const fetchMock = async () => {
    setSyntacticData([[], [], [], [], []]);
    const res = await fetch("/api/ldp-mock", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        prompt: z.string().parse(prompt),
      }),
    });

    const data = (await res.json()) as Array<Array<string>>;

    setPrompt("Loading...");
    await sleep(7000);
    setPrompt("");
    data.forEach((sentence, i) => {
      appendTextToData(sentence, i);
    });
  };

  const appendTextToData = async (sentence: Array<string>, index: number) => {
    for (const word of sentence) {
      await sleep(Math.random() * 900);
      const clone = getSyntacticData().slice();
      (clone[index] as Array<string>).push(word);
      setSyntacticData(clone);
    }
  };

  return (
    <>
      <Head>
        <title>SCB 10x Hackathon Showcase</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={""}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <style>{"body { background-color: #060606; }"}</style>
      </Head>
      <main>
        <div
          // Frame 22
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            padding: 24,
            gap: 24,
          }}
        >
          <h2
            style={{
              color: "#fff",
              textAlign: "center",
              fontFamily: "Dosis",
              fontSize: 64,
              fontStyle: "normal",
              fontWeight: 600,
              lineHeight: "normal",
              margin: 0,
            }}
          >
            LDP and DP-GANs
          </h2>
          <div
            //  Frame 21
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              gap: 24,
            }}
          >
            <div
              // Frame 18
              style={{
                display: "flex",
                width: "296px",
                justifyContent: "center",
                alignItems: "flex-start",
              }}
            >
              <div
                // Frame 17
                style={{
                  display: "flex",
                  padding: "16px 24px",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: "8px",
                  flex: "1 0 0",
                  borderRadius: "12px 0px 0px 12px",
                  background: "#FBAE17",
                }}
              >
                <Link
                  style={{
                    color: "#543904",
                    fontFamily: "Dosis",
                    fontSize: "24px",
                    fontStyle: "normal",
                    fontWeight: 700,
                    lineHeight: "normal",
                    margin: 0,
                  }}
                  href={"/ldp"}
                >
                  LDP
                </Link>
              </div>
              <div
                // Frame 2
                style={{
                  display: "flex",
                  padding: "16px 24px",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: "8px",
                  flex: "1 0 0",
                  borderRadius: "0 12px 12px 0px",
                  border: "1px solid #666",
                  background: "#1F1F1F",
                }}
              >
                <Link
                  style={{
                    color: "#FFF",
                    fontFamily: "Dosis",
                    fontSize: "24px",
                    fontStyle: "normal",
                    fontWeight: 700,
                    lineHeight: "normal",
                    margin: 0,
                  }}
                  href={"/"}
                >
                  DP-GANs
                </Link>
              </div>
            </div>
            <p
              style={{
                color: "#FFF",
                textAlign: "justify",
                fontFamily: "Dosis",
                fontSize: "24px",
                fontStyle: "normal",
                fontWeight: 600,
                lineHeight: "normal",
                width: 1344,
                margin: 0,
              }}
            >
              Existing text generation methods tend to produce repeated and
              "boring" expressions. To tackle this problem, we propose a new
              text generation model, called Diversity-Promoting Generative
              Adversarial Network (DP-GAN). The proposed model assigns low
              reward for repeatedly generated text and high reward for "novel"
              and fluent text, encouraging the generator to produce diverse and
              informative text.
            </p>
            <div
              // Frame 16
              style={{
                display: "flex",
                width: "1344px",
                marginBottom: "100px",
                flexDirection: "column",
                alignItems: "flex-start",
                gap: "16px",
              }}
            >
              <div
                // Frame 3
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "16px",
                  alignSelf: "stretch",
                }}
              >
                <input
                  // Frame 1
                  style={{
                    display: "flex",
                    padding: "16px 24px",
                    alignItems: "center",
                    gap: "8px",
                    flex: "1 0 auto",
                    borderRadius: "12px",
                    border: "1px solid #666",
                    background: "#1F1F1F",

                    color: "#FFF",
                    fontFamily: "Dosis",
                    fontSize: "24px",
                    fontStyle: "normal",
                    fontWeight: 500,
                    lineHeight: "normal",
                  }}
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                />
                <button
                  // Frame 2
                  style={{
                    display: "flex",
                    padding: "16px 24px",
                    alignItems: "center",
                    gap: "8px",
                    borderRadius: "12px",
                    background: "#4B2884",
                    borderWidth: 0,
                  }}
                  onClick={fetchMock}
                >
                  <p
                    style={{
                      color: "#DECEF9",
                      fontFamily: "Dosis",
                      fontSize: "24px",
                      fontStyle: "normal",
                      fontWeight: 700,
                      lineHeight: "normal",
                      margin: 0,
                    }}
                  >
                    Generate Data
                  </p>
                </button>
              </div>
              {(syntacticData[0] as Array<string>).length !== 0 && (
                <div
                  // Frame 15
                  style={{
                    display: "flex",
                    padding: "32px",
                    flexDirection: "column",
                    alignItems: "flex-start",
                    gap: "16px",
                    flex: "1 0 auto",
                    alignSelf: "stretch",
                    borderRadius: "12px",
                    border: "1px solid #666",
                    background: "#1F1F1F",
                  }}
                >
                  {syntacticData.map((data, i) => {
                    return (
                      <div
                        key={i}
                        style={{
                          display: "flex",
                          padding: "20px",
                          alignItems: "center",
                          gap: "8px",
                          alignSelf: "stretch",
                          borderRadius: "20px",
                          border: "1px solid #494651",
                          background: "#3E3A4B",
                        }}
                      >
                        <p
                          key={i}
                          style={{
                            flex: "1 0 0",
                            color: "#FFF",
                            fontFamily: "Dosis",
                            fontSize: "20",
                            fontStyle: "normal",
                            fontWeight: "600",
                            lineHeight: "normal",
                          }}
                        >
                          {data}
                        </p>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
